### PR TITLE
add swal shorthand support

### PR DESCRIPTION
**Pull request by TheRusskiy**
Right now you can only call
```
swal(
  title:  'Oops...',
  text: 'Something went wrong!',
  type: 'error'
)
```
after this commit you can use the shorthand version
`swal('Oops...',  'Something went wrong!', 'error')`

### CODE REVIEW

**Comment by matheuslc** [comment]
I prefer to use a more explict way to declare these attributes. But I dont't see any problem for now.

What do you think about it @nathanmarcos @williamthiago?

**Comment by nathanmarcos** [comment]
I agree with @matheuslc.

@TheRusskiy Thanks for your contribution!

**Comment by TheRusskiy** [comment]
@matheuslc @nathanmarcos while explicit way to call swal may be preferable in many cases, IMHO it's good to adhere to swal's documentation (especially that it's explicitly referenced as a source of truth in readme) and let it be called using the shorthand version if a developer prefers it.
Sorry for the delayed response.

**Comment by cassiosantos** [comment]
Thank you for your contribution!

I'm closing this PR because the library is no longer under development/maintenance at SocialBase.

**Pull request closed without merging**
